import { existsSync, readdirSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { detectWorkspace, findConfig, loadConfig, resolveKitsPath } from '../../lib/workspace.js';

const KIT_DESCRIPTIONS: Record<string, string> = {
  email: 'Full-featured email client with folders, threads, compose dialog, labels, and responsive layout.',
  kanban: 'Drag-and-drop kanban board with columns, tasks, priorities, assignees, and labels.',
};

const KIT_COMPONENTS: Record<string, string[]> = {
  email: ['EmailKit', 'FivFoldEmailFolder', 'FivFoldEmailThread', 'FivFoldEmailMessage', 'FivFoldEmailProps'],
  kanban: ['KanbanKit', 'FivFoldKanbanColumn', 'FivFoldKanbanTask', 'FivFoldKanbanProps'],
};

export function generateAgentsMd(force: boolean): void {
  const workspace = detectWorkspace();
  const configPath = findConfig(workspace);
  const config = configPath ? loadConfig(configPath) : null;

  const outputPath = join(workspace.root, 'AGENTS.md');

  if (existsSync(outputPath) && !force) {
    console.log('\n  AGENTS.md already exists. Use --force to overwrite.\n');
    return;
  }

  // Detect installed kits
  const installedKits: string[] = [];
  if (config) {
    const kitsDir = resolveKitsPath(config, workspace);
    if (existsSync(kitsDir)) {
      const entries = readdirSync(kitsDir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.isDirectory()) installedKits.push(entry.name);
      }
    }
  }

  const kitsAlias = config?.aliases.kits ?? '@/components/ui/kits';
  const uiAlias = config?.aliases.ui ?? '@/components/ui';
  const style = config?.style ?? 'mesa';
  const baseColor = config?.theme.baseColor ?? 'neutral';
  const themeSource = config?.theme.source ?? 'fivfold';
  const font = config?.font ?? 'inter';

  const kitSections = installedKits.length > 0
    ? installedKits.map((name) => {
        const desc = KIT_DESCRIPTIONS[name] ?? `${name} Kit`;
        const components = KIT_COMPONENTS[name] ?? [`${name.charAt(0).toUpperCase() + name.slice(1)}Kit`];
        return `### ${name.charAt(0).toUpperCase() + name.slice(1)} Kit

**Location:** \`${kitsAlias}/${name}/index.tsx\`
**Description:** ${desc}

**Exports:**
${components.map((c) => `- \`${c}\``).join('\n')}

**Usage:**
\`\`\`tsx
import { ${components[0]} } from "${kitsAlias}/${name}"
\`\`\``;
      }).join('\n\n')
    : '_No Kits installed yet. Run `npx @fivfold/ui add email` to get started._';

  const content = `# AGENTS.md

> Generated by FivFold. Keep this file updated as your project evolves.
> Supported by: Cursor, GitHub Copilot, Windsurf, Claude Code, Cline, Gemini CLI, and all AGENTS.md-compatible AI assistants.

## Project Overview

This project uses **FivFold** -- a full-stack Kit platform built on top of **shadcn/ui**.

- **FivFold UI Kits** are pre-built, fully-responsive feature blocks (e.g. email client, kanban board)
- **shadcn/ui** provides the underlying UI primitives (Button, Card, Dialog, etc.)
- **Tailwind CSS v4** handles all styling via CSS variables
- **TypeScript** is used throughout

---

## Key Conventions

### Import Paths

| Purpose | Import Path |
|---------|-------------|
| shadcn/ui components | \`${uiAlias}/<component>\` |
| FivFold Kits | \`${kitsAlias}/<name>\` |
| Utilities (cn) | \`${config?.aliases.utils ?? '@/lib/utils'}\` |
| Hooks | \`${config?.aliases.hooks ?? '@/hooks'}/<hook>\` |

### Component Rules

- All shadcn/ui components live in \`${uiAlias}/\` -- **never modify these files directly**
- Kits live in \`${kitsAlias}/\` -- these CAN be modified to fit your needs
- Use \`cn()\` from \`${config?.aliases.utils ?? '@/lib/utils'}\` for conditional class merging
- Client components MUST have \`"use client"\` at the top
- Server components should NOT have \`"use client"\`

---

## Theming

- **Theme source:** ${themeSource === 'fivfold' ? 'FivFold (managed)' : 'shadcn/ui (existing)'}
- **Base color:** ${baseColor}
- **Style preset:** ${style}
- **Font:** ${font}
- **CSS file:** \`${config?.theme.css ?? 'src/styles/globals.css'}\`

### CSS Variables

All colors use standard shadcn/ui CSS variables defined in the global CSS file:

\`\`\`css
/* Core semantic tokens (shadcn/ui) */
--background    --foreground
--card          --card-foreground
--primary       --primary-foreground
--secondary     --secondary-foreground
--muted         --muted-foreground
--accent        --accent-foreground
--destructive   --destructive-foreground
--border        --input        --ring
--sidebar-*     --chart-*
\`\`\`

When styling components:
- Use Tailwind semantic classes: \`bg-background\`, \`text-foreground\`, \`bg-card\`, \`text-muted-foreground\`, \`bg-primary\`, etc.
- Do NOT use hardcoded color classes like \`bg-green-100\` or \`text-blue-500\` inside Kits -- use CSS variable-based classes instead

---

## Installed Kits

${kitSections}

---

## File Structure

\`\`\`
src/
  components/
    ui/               # shadcn/ui components (do not modify)
      button.tsx
      card.tsx
      dialog.tsx
      ...
    ui/kits/          # FivFold Kits (can be customized)
${installedKits.map((n) => `      ${n}/\n        index.tsx`).join('\n')}
  lib/
    utils.ts          # cn() utility
  hooks/
    ...
  styles/
    globals.css       # Tailwind + theme CSS variables
\`\`\`

---

## Adding More Kits

\`\`\`bash
npx @fivfold/ui list              # see all available Kits
npx @fivfold/ui add <name>        # add a Kit
npx @fivfold/ui add <name> --theme zinc  # add with a specific theme
\`\`\`

## Backend API Modules

FivFold also provides backend scaffolding via \`@fivfold/api\`:

\`\`\`bash
npx @fivfold/api init             # configure backend (framework, ORM, database)
npx @fivfold/api add email        # scaffold email API module
npx @fivfold/api add kanban       # scaffold kanban API module
\`\`\`

Each API module generates entities, DTOs, services, and controllers. See the generated \`README.md\` inside each module folder for integration instructions.

---

## Development Standards

- **TypeScript:** strict mode, no \`any\` unless absolutely necessary
- **React:** functional components with hooks, no class components
- **State:** local state with \`useState\`/\`useReducer\`, server state with your preferred library
- **Forms:** use controlled components with \`onChange\` handlers
- **Accessibility:** Kits use Radix UI primitives via shadcn/ui -- maintain ARIA attributes
- **Responsiveness:** Kits are mobile-first; test at 375px, 768px, 1280px
- **Dark mode:** Kits support dark mode via Tailwind's \`dark:\` variant and CSS variables
`;

  writeFileSync(outputPath, content, 'utf8');
  console.log(`\n  Created AGENTS.md at ${outputPath}`);
  console.log('  AI assistants will use this file to understand your FivFold setup.\n');
}
