import type {
  FivFoldKanbanColumn,
  FivFoldKanbanLabel,
} from "@/components/ui/kits/kanban"

export const MOCK_KANBAN_LABELS: FivFoldKanbanLabel[] = [
  { id: "design", name: "Design", color: "#8b5cf6" },
  { id: "ux", name: "UX", color: "#06b6d4" },
  { id: "backend", name: "Backend", color: "#f59e0b" },
  { id: "frontend", name: "Frontend", color: "#3b82f6" },
  { id: "devops", name: "DevOps", color: "#ef4444" },
  { id: "infrastructure", name: "Infrastructure", color: "#84cc16" },
  { id: "docs", name: "Docs", color: "#22c55e" },
  { id: "auth", name: "Auth", color: "#ec4899" },
  { id: "refactor", name: "Refactor", color: "#f97316" },
  { id: "setup", name: "Setup", color: "#64748b" },
]

const labelById = Object.fromEntries(
  MOCK_KANBAN_LABELS.map((l) => [l.id, l])
) as Record<string, FivFoldKanbanLabel>

function labels(...ids: string[]): FivFoldKanbanLabel[] {
  return ids.map((id) => labelById[id]).filter(Boolean)
}

export const MOCK_KANBAN_COLUMNS: FivFoldKanbanColumn[] = [
  {
    id: "todo",
    title: "To Do",
    description: "Tasks to be done",
    color: "#64748b",
    tasks: [
      {
        id: "t1",
        taskId: "KAN-001",
        title: "Design user onboarding flow",
        description:
          "Create wireframes and user journey for new sign-ups. Include first-time experience, empty states, and success metrics.",
        status: "todo",
        priority: "high",
        assignee: { id: "u1", name: "Alex Chen", initials: "AC" },
        reporter: { id: "u3", name: "Jordan Lee", initials: "JL" },
        dueDate: "2025-03-15",
        storyPoints: 5,
        sprint: "Sprint 1",
        labels: labels("design", "ux"),
        createdAt: "2025-03-01T10:00:00Z",
        updatedAt: "2025-03-01T10:00:00Z",
      },
      {
        id: "t2",
        taskId: "KAN-002",
        title: "Set up CI/CD pipeline",
        description:
          "Configure GitHub Actions for automated testing and deployment. Include unit tests, E2E, and staging deploy.",
        status: "todo",
        priority: "urgent",
        assignee: { id: "u2", name: "Sam Rivera", initials: "SR" },
        reporter: { id: "u1", name: "Alex Chen", initials: "AC" },
        storyPoints: 8,
        sprint: "Sprint 1",
        labels: labels("devops", "infrastructure"),
        createdAt: "2025-03-02T14:30:00Z",
        updatedAt: "2025-03-02T14:30:00Z",
      },
      {
        id: "t3",
        taskId: "KAN-003",
        title: "Write API documentation",
        description: "OpenAPI spec and developer guide for public endpoints.",
        status: "todo",
        priority: "medium",
        reporter: { id: "u2", name: "Sam Rivera", initials: "SR" },
        storyPoints: 3,
        sprint: "Sprint 1",
        labels: labels("docs"),
        createdAt: "2025-03-03T09:00:00Z",
        updatedAt: "2025-03-03T09:00:00Z",
      },
      {
        id: "t8",
        taskId: "KAN-008",
        title: "User research interviews",
        description: "Conduct 5 user interviews to validate onboarding assumptions.",
        status: "todo",
        priority: "medium",
        assignee: { id: "u1", name: "Alex Chen", initials: "AC" },
        dueDate: "2025-03-18",
        storyPoints: 3,
        sprint: "Sprint 1",
        labels: labels("ux", "design"),
        createdAt: "2025-03-05T11:00:00Z",
        updatedAt: "2025-03-05T11:00:00Z",
      },
    ],
  },
  {
    id: "in-progress",
    title: "In Progress",
    description: "Currently being worked on",
    color: "#3b82f6",
    tasks: [
      {
        id: "t4",
        taskId: "KAN-004",
        title: "Implement auth middleware",
        description:
          "JWT verification and role-based access control. Support refresh tokens and session invalidation.",
        status: "in-progress",
        priority: "high",
        assignee: { id: "u1", name: "Alex Chen", initials: "AC" },
        reporter: { id: "u2", name: "Sam Rivera", initials: "SR" },
        estimatedHours: 8,
        actualHours: 4,
        storyPoints: 5,
        sprint: "Sprint 1",
        labels: labels("backend", "auth"),
        createdAt: "2025-03-04T11:00:00Z",
        updatedAt: "2025-03-05T16:00:00Z",
      },
      {
        id: "t5",
        taskId: "KAN-005",
        title: "Build dashboard layout",
        description: "Responsive layout with sidebar navigation and breadcrumbs.",
        status: "in-progress",
        priority: "medium",
        assignee: { id: "u3", name: "Jordan Lee", initials: "JL" },
        reporter: { id: "u1", name: "Alex Chen", initials: "AC" },
        storyPoints: 5,
        sprint: "Sprint 1",
        labels: labels("frontend"),
        createdAt: "2025-03-05T08:00:00Z",
        updatedAt: "2025-03-05T12:00:00Z",
      },
      {
        id: "t9",
        taskId: "KAN-009",
        title: "Database schema migration",
        description: "Add users and sessions tables with indexes.",
        status: "in-progress",
        priority: "high",
        assignee: { id: "u2", name: "Sam Rivera", initials: "SR" },
        estimatedHours: 4,
        actualHours: 2,
        storyPoints: 3,
        sprint: "Sprint 1",
        labels: labels("backend", "infrastructure"),
        createdAt: "2025-03-06T09:00:00Z",
        updatedAt: "2025-03-06T14:00:00Z",
      },
    ],
  },
  {
    id: "review",
    title: "Review",
    description: "Awaiting code review",
    color: "#f59e0b",
    tasks: [
      {
        id: "t6",
        taskId: "KAN-006",
        title: "Refactor data fetching hooks",
        description:
          "Consolidate useQuery patterns and error handling. Add retry logic and optimistic updates.",
        status: "review",
        priority: "low",
        assignee: { id: "u2", name: "Sam Rivera", initials: "SR" },
        reporter: { id: "u3", name: "Jordan Lee", initials: "JL" },
        storyPoints: 3,
        sprint: "Sprint 1",
        labels: labels("frontend", "refactor"),
        comments: 2,
        createdAt: "2025-03-06T10:00:00Z",
        updatedAt: "2025-03-06T15:00:00Z",
      },
    ],
  },
  {
    id: "done",
    title: "Done",
    description: "Completed tasks",
    color: "#22c55e",
    tasks: [
      {
        id: "t7",
        taskId: "KAN-007",
        title: "Initial project setup",
        description:
          "Next.js, Tailwind, ESLint, TypeScript config. Monorepo structure with shared packages.",
        status: "done",
        priority: "medium",
        assignee: { id: "u3", name: "Jordan Lee", initials: "JL" },
        reporter: { id: "u1", name: "Alex Chen", initials: "AC" },
        storyPoints: 5,
        sprint: "Sprint 0",
        labels: labels("setup"),
        createdAt: "2025-02-28T09:00:00Z",
        updatedAt: "2025-03-01T17:00:00Z",
      },
    ],
  },
]
