"use client";

import Link from "next/link";
import { CodeBlock } from "../../../components/code-block";
import { DocCallout } from "../../../components/doc-blocks";
import { useStack } from "../../../components/stack-context";
import { KitFeBeConnectionGuide } from "../../../components/kit-fe-be-connection";
import { KitIntegrationDisclaimer } from "../../../components/kit-integration-disclaimer";

const SHADCN_PRIMITIVES_TABLE = (
  <div className="overflow-x-auto rounded-lg border border-white/10">
    <table className="w-full text-sm border-collapse">
      <thead>
        <tr className="border-b border-white/10">
          <th className="text-left py-2 px-3 font-medium text-white/80">Primitive</th>
          <th className="text-left py-2 px-3 font-medium text-white/80">Used for</th>
        </tr>
      </thead>
      <tbody className="text-white/70">
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">dialog</td><td className="py-2 px-3">New chat, search, GIF, location, polls, attachments</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">tabs</td><td className="py-2 px-3">Tabbed dialogs</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">separator</td><td className="py-2 px-3">Layout dividers</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">scroll-area</td><td className="py-2 px-3">Scrollable lists</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">input</td><td className="py-2 px-3">Text fields</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">textarea</td><td className="py-2 px-3">Composer</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">label</td><td className="py-2 px-3">Form labels</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">badge</td><td className="py-2 px-3">Thread metadata</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">tooltip</td><td className="py-2 px-3">Toolbar hints — wrap the app in <code className="rounded bg-white/10 px-1">TooltipProvider</code></td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">dropdown-menu</td><td className="py-2 px-3">Thread row ⋯ menu, sidebar overflow, chat header ⋯ menu</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">context-menu</td><td className="py-2 px-3">Thread / message actions (right-click)</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">alert-dialog</td><td className="py-2 px-3">Destructive confirms (e.g. leave group)</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">switch</td><td className="py-2 px-3">Poll options</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">progress</td><td className="py-2 px-3">Poll UI</td></tr>
        <tr className="border-b border-white/5"><td className="py-2 px-3 font-mono text-brand-secondary">button</td><td className="py-2 px-3">Everywhere</td></tr>
      </tbody>
    </table>
  </div>
);

/** Exported for Chat UI tab §7 (shadcn primitives) — see AGENTS.md kit doc structure. */
export function ChatKitShadcnPrimitivesSection() {
  return (
    <div className="space-y-3">
      <p className="text-white/65 text-sm mb-3">
        <code className="rounded bg-white/10 px-1">npx @fivfold/ui add chat</code> runs <code className="rounded bg-white/10 px-1">shadcn add</code> for the list below. If anything is missing, run the same command manually from the{" "}
        <strong className="text-white/85">project root where <code className="rounded bg-white/10 px-1">components.json</code> lives</strong> so paths resolve (see troubleshooting in full-stack integration).
      </p>
      {SHADCN_PRIMITIVES_TABLE}
    </div>
  );
}

/** UI tab — dev routing + browser wiring not generated by FivFold. */
export function ChatFullstackUiGuide({ embedded }: { embedded?: boolean }) {
  const { stack } = useStack();
  const fe = stack.frontend;
  const isNext = fe === "nextjs";

  return (
    <div
      className={
        embedded
          ? "space-y-8"
          : "space-y-8 border-t border-white/10 pt-10 mt-10"
      }
    >
      <KitIntegrationDisclaimer />

      <div id="fullstack-checklist" className="scroll-mt-28">
        <DocCallout variant="info" title="After you add Chat UI + Chat API — checklist">
          <p className="text-white/70 text-sm mb-3">
            Scaffolding aligns routes and dependencies; your app still needs a thin integration layer. Work through these in order for local dev:
          </p>
          <ol className="list-decimal space-y-2 pl-4 text-sm text-white/75">
            <li>
              <strong className="text-white/85">Identity on the API:</strong> Nest registers <code className="rounded bg-white/10 px-1">ChatModule</code> but does not auto-wire{" "}
              <code className="rounded bg-white/10 px-1">ChatDevUserMiddleware</code> in <code className="rounded bg-white/10 px-1">main.ts</code>. Either register it (see below) or use real auth so{" "}
              <code className="rounded bg-white/10 px-1">req.user.id</code> exists — otherwise REST handlers throw at runtime.
            </li>
            <li>
              <strong className="text-white/85">Socket.IO through the dev server:</strong>{" "}
              {isNext ? (
                <>Add a rewrite for <code className="rounded bg-white/10 px-1">/socket.io</code> to your API (same idea as REST), or point <code className="rounded bg-white/10 px-1">socket.io-client</code> at the API origin.</>
              ) : (
                <>Proxy <code className="rounded bg-white/10 px-1">/socket.io</code> with <code className="rounded bg-white/10 px-1">ws: true</code> in <code className="rounded bg-white/10 px-1">vite.config</code>, or connect the client directly to your API URL (e.g. env).</>
              )}
            </li>
            <li>
              <strong className="text-white/85">Same user id everywhere:</strong> send <code className="rounded bg-white/10 px-1">X-User-Id</code> on fetch (or JWT) matching <code className="rounded bg-white/10 px-1">currentUser.id</code> in the kit and the server&apos;s dev default / env (<code className="rounded bg-white/10 px-1">DEV_USER_ID</code>).
            </li>
            <li>
              <strong className="text-white/85">Integration host:</strong> <code className="rounded bg-white/10 px-1">ChatKit</code> is presentational — add a page or module that loads conversations/messages from your API, maps DTOs to <code className="rounded bg-white/10 px-1">FivFoldChat*</code> types, and implements{" "}
              <code className="rounded bg-white/10 px-1">onSendMessage</code>, search, and socket listeners (see examples below).
            </li>
            <li>
              Generic FE ↔ BE patterns (proxy, CORS) also apply — see{" "}
              <Link href="/docs/getting-started/installation#connecting-ui-and-api" className="text-brand-primary underline-offset-2 hover:underline">
                Installation → Connecting UI and API
              </Link>
              .
            </li>
          </ol>
        </DocCallout>
      </div>

      <div>
        <h3 className="text-lg font-semibold text-white mb-2">Full-stack local dev (your app code)</h3>
        <p className="text-white/65 text-sm leading-relaxed mb-4">
          FivFold adds the <strong className="text-white/85">ChatKit</strong> components and installs dependencies. Everything below is{" "}
          <strong className="text-white/85">outside</strong> the kit: dev-server routing to your API, env vars, fetch/socket helpers, and a thin host that maps API DTOs to{" "}
          <code className="rounded bg-white/10 px-1">FivFoldChat*</code> types. Match the <strong className="text-white/85">Frontend</strong> choice in the stack sidebar (
          {isNext ? "Next.js" : "Vite"}).
        </p>
        <DocCallout variant="warning" title="Not for production as-is">
          The patterns below use a dev user header and permissive CORS. Replace with JWT (or your Auth kit) before shipping.
        </DocCallout>
      </div>

      <KitFeBeConnectionGuide
        withDisclaimer={false}
        kitTitle="Chat"
        apiControllerPath="chat"
        realtimeNote={
          isNext
            ? "For Socket.IO with Next.js dev, rewrite `/socket.io` to your API host (same pattern as REST) or use a server that shares the HTTP server with Socket.IO."
            : "Proxy `/socket.io` with `ws: true` to the same host/port as your Chat REST API so `socket.io-client` can upgrade through the Vite dev server."
        }
      />

      <div>
        <h4 className="font-semibold text-white mb-2">
          {isNext ? "Next.js rewrites (Chat + Socket.IO)" : "Vite proxy (Chat + Socket.IO)"}
        </h4>
        <p className="text-white/65 text-sm mb-3">
          Browser code should call <code className="rounded bg-white/10 px-1">/api/chat/...</code>.{" "}
          {isNext ? (
            <>
              Use <code className="rounded bg-white/10 px-1">rewrites</code> so the Next dev server forwards to your API. Add a second rule for{" "}
              <code className="rounded bg-white/10 px-1">/socket.io</code> if the client connects through the app origin.
            </>
          ) : (
            <>
              Proxy <code className="rounded bg-white/10 px-1">/api</code> to your API and{" "}
              <strong className="text-white/85">strip the <code className="rounded bg-white/10 px-1">/api</code> prefix</strong> if Nest has no global prefix (so{" "}
              <code className="rounded bg-white/10 px-1">/api/chat/conversations</code> → <code className="rounded bg-white/10 px-1">/chat/conversations</code>). Proxy{" "}
              <code className="rounded bg-white/10 px-1">/socket.io</code> with <code className="rounded bg-white/10 px-1">ws: true</code>.
            </>
          )}
        </p>
        {isNext ? (
          <CodeBlock
            code={`// next.config.ts — Chat REST + Socket.IO through dev server (example)
import type { NextConfig } from 'next';

const API = process.env.CHAT_DEV_API ?? 'http://localhost:3001';

const nextConfig: NextConfig = {
  async rewrites() {
    return [
      { source: '/api/:path*', destination: API + '/:path*' },
      { source: '/socket.io/:path*', destination: API + '/socket.io/:path*' },
    ];
  },
};

export default nextConfig;`}
            language="ts"
            filename="next.config.ts"
          />
        ) : (
          <CodeBlock
            code={`// vite.config.ts (example)
export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/api': {
        target: process.env.VITE_DEV_API_PROXY ?? 'http://localhost:3000',
        changeOrigin: true,
        rewrite: (p) => p.replace(/^\\/api/, ''),
      },
      '/socket.io': {
        target: process.env.VITE_DEV_API_PROXY ?? 'http://localhost:3000',
        changeOrigin: true,
        ws: true,
      },
    },
  },
});`}
            language="ts"
            filename="vite.config.ts"
          />
        )}
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">Environment variables (frontend)</h4>
        <div className="overflow-x-auto rounded-lg border border-white/10 text-sm">
          <table className="w-full border-collapse text-white/75">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-2 px-3 font-medium text-white/80">Variable</th>
                <th className="text-left py-2 px-3 font-medium text-white/80">Role</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-white/5">
                <td className="py-2 px-3 font-mono text-brand-secondary">
                  {isNext ? "NEXT_PUBLIC_CHAT_DEV_USER_ID" : "VITE_DEV_USER_ID"}
                </td>
                <td className="py-2 px-3">
                  Must match the API “current user” (same value as <code className="rounded bg-white/10 px-1">X-User-Id</code> header and server default, e.g.{" "}
                  <code className="rounded bg-white/10 px-1">dev-user-local</code>). Name it however you like in your own <code className="rounded bg-white/10 px-1">apiUrl</code> helper.
                </td>
              </tr>
              <tr className="border-b border-white/5">
                <td className="py-2 px-3 font-mono text-brand-secondary">
                  {isNext ? "NEXT_PUBLIC_API_URL" : "VITE_API_ORIGIN"}
                </td>
                <td className="py-2 px-3">
                  Optional production API base. If empty, use same-origin <code className="rounded bg-white/10 px-1">/api/...</code> (rewrites/proxy in dev).
                </td>
              </tr>
              <tr className="border-b border-white/5">
                <td className="py-2 px-3 font-mono text-brand-secondary">
                  {isNext ? "NEXT_PUBLIC_SOCKET_ORIGIN" : "VITE_SOCKET_ORIGIN"}
                </td>
                <td className="py-2 px-3">
                  Optional; default <code className="rounded bg-white/10 px-1">window.location.origin</code> so Socket.IO goes through the app dev server.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">API + Socket helpers (you implement)</h4>
        <p className="text-white/65 text-sm mb-3">
          Add small modules in <strong className="text-white/85">your</strong> repo, e.g. <code className="rounded bg-white/10 px-1">src/lib/api.ts</code> with{" "}
          <code className="rounded bg-white/10 px-1">fivFoldUserId()</code>, <code className="rounded bg-white/10 px-1">fivFoldAuthHeaders()</code> (<code className="rounded bg-white/10 px-1">X-User-Id</code>), and{" "}
          <code className="rounded bg-white/10 px-1">apiUrl(path)</code>. Use <code className="rounded bg-white/10 px-1">socket.io-client</code> with{" "}
          <code className="rounded bg-white/10 px-1">
            {'io(`${origin}/chat`, { path: \'/socket.io\', query: { userId } })'}
          </code>{" "}
          — namespace <code className="rounded bg-white/10 px-1">/chat</code> and path{" "}
          <code className="rounded bg-white/10 px-1">/socket.io</code> must match the Nest gateway.
        </p>
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">Integration host (you implement)</h4>
        <p className="text-white/65 text-sm mb-3">
          One component (e.g. <code className="rounded bg-white/10 px-1">src/integration/fivfold-chat-host.tsx</code>) should load conversations/messages from REST, map DTOs to kit types, pass callbacks that <code className="rounded bg-white/10 px-1">fetch</code> the Chat API, and subscribe to{" "}
          <code className="rounded bg-white/10 px-1">message:new</code> / typing events. If list endpoints omit <code className="rounded bg-white/10 px-1">participants</code>, synthesize minimal participant rows for avatars or extend your API.
        </p>
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">TypeScript strict / shadcn quirks</h4>
        <ul className="list-disc pl-5 text-white/65 text-sm space-y-2">
          <li>
            <strong className="text-white/85">Stray <code className="rounded bg-white/10 px-1">@</code> folder:</strong> If shadcn created <code className="rounded bg-white/10 px-1">@/components/...</code> on disk, ensure{" "}
            <code className="rounded bg-white/10 px-1">components.json</code> aliases match <code className="rounded bg-white/10 px-1">tsconfig</code> paths. FivFold&apos;s <code className="rounded bg-white/10 px-1">add</code> command attempts to merge misplaced files into{" "}
            <code className="rounded bg-white/10 px-1">src/components/ui</code>.
          </li>
          <li>
            <strong className="text-white/85"><code className="rounded bg-white/10 px-1">noUnusedLocals</code>:</strong> Strict projects may need relaxed rules for generated kit folders, or enable incremental cleanup.
          </li>
          <li>
            <strong className="text-white/85">Dialog close button:</strong> Newer shadcn uses <code className="rounded bg-white/10 px-1">showCloseButton</code>; the kit templates use that API.
          </li>
        </ul>
      </div>
    </div>
  );
}

/** API tab — Nest/Express bootstrap not fully generated. */
export function ChatFullstackApiGuide({ isNestJS }: { isNestJS: boolean }) {
  const { stack } = useStack();
  const isNext = stack.frontend === "nextjs";
  const corsOriginLines = isNext
    ? `      'http://localhost:3000',\n      'http://127.0.0.1:3000',`
    : `      'http://localhost:5173',\n      'http://127.0.0.1:5173',`;
  const feLabel = isNext ? "Next.js (e.g. localhost:3000)" : "Vite (e.g. localhost:5173)";

  if (!isNestJS) {
    return (
      <div className="space-y-6 border-t border-white/10 pt-10 mt-10">
        <KitIntegrationDisclaimer />
        <h3 className="text-lg font-semibold text-white mb-2">Full-stack local dev (Express)</h3>
        <p className="text-white/65 text-sm">
          Mirror the same ideas: set <code className="rounded bg-white/10 px-1">req.user.id</code> in dev (middleware reading <code className="rounded bg-white/10 px-1">X-User-Id</code> / <code className="rounded bg-white/10 px-1">DEV_USER_ID</code>), enable CORS for your web app origin ({feLabel}, matching the stack <strong className="text-white/80">Frontend</strong> selection), attach Socket.IO on the same HTTP server. Pass the namespace returned by{" "}
          <code className="rounded bg-white/10 px-1">initChatSocketHandlers(io, chatService)</code> into{" "}
          <code className="rounded bg-white/10 px-1">createChatRouter(chatService, chatNamespace)</code> so REST POST{" "}
          <code className="rounded bg-white/10 px-1">/messages</code> emits <code className="rounded bg-white/10 px-1">message:new</code>.
        </p>
        <p className="text-white/65 text-sm">
          See the <strong className="text-white/85">UI tab</strong> for {isNext ? "Next rewrites" : "Vite proxy"} and env alignment.
        </p>
      </div>
    );
  }

  const nestMainSnippet = `import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { IoAdapter } from '@nestjs/platform-socket.io';
import { AppModule } from './app.module';
import { ChatDevUserMiddleware } from './modules/chat/chat-dev-user.middleware';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  app.useWebSocketAdapter(new IoAdapter(app));

  app.enableCors({
    origin: [
${corsOriginLines}
      ...(process.env.CORS_ORIGIN?.split(',').map((o) => o.trim()) ?? []),
    ],
    credentials: true,
  });

  const devUser = new ChatDevUserMiddleware();
  app.use(devUser.use.bind(devUser));

  await app.listen(process.env.PORT ?? 3000);
}
bootstrap();`;

  return (
    <div className="space-y-8 border-t border-white/10 pt-10 mt-10">
      <KitIntegrationDisclaimer />

      <div>
        <h3 className="text-lg font-semibold text-white mb-2">Full-stack local dev (NestJS)</h3>
        <p className="text-white/65 text-sm leading-relaxed mb-4">
          Generated module: <code className="rounded bg-white/10 px-1">chat-dev-user.middleware.ts</code> (optional). <strong className="text-white/85">REST</strong>{" "}
          <code className="rounded bg-white/10 px-1">POST /chat/messages</code> persists then emits <code className="rounded bg-white/10 px-1">message:new</code> to the conversation room so clients match WebSocket sends.
        </p>
        <DocCallout variant="warning" title="Dev middleware only">
          Remove <code className="rounded bg-white/10 px-1">ChatDevUserMiddleware</code> when you add JWT; use guards that populate <code className="rounded bg-white/10 px-1">req.user</code>.
        </DocCallout>
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">Bootstrap snippet (<code className="text-brand-secondary">main.ts</code>)</h4>
        <p className="text-white/55 text-xs mb-2">
          CORS defaults match <strong className="text-white/70">{feLabel}</strong> from the stack sidebar; extend with <code className="rounded bg-white/10 px-1">CORS_ORIGIN</code>.
        </p>
        <CodeBlock code={nestMainSnippet} language="ts" filename="src/main.ts" />
        <p className="text-white/50 text-xs mt-2">
          Adjust import path to your chat module. Resolution order: <code className="rounded bg-white/10 px-1">X-User-Id</code> → <code className="rounded bg-white/10 px-1">DEV_USER_ID</code> →{" "}
          <code className="rounded bg-white/10 px-1">dev-user-local</code>.
        </p>
      </div>

      <div>
        <h4 className="font-semibold text-white mb-2">Socket contract</h4>
        <p className="text-white/65 text-sm">
          Gateway namespace <code className="rounded bg-white/10 px-1">/chat</code>, Socket.IO path <code className="rounded bg-white/10 px-1">/socket.io</code>, handshake query{" "}
          <code className="rounded bg-white/10 px-1">userId</code>. Client should join rooms via <code className="rounded bg-white/10 px-1">conversation:join</code> after opening a thread.
        </p>
      </div>

      <p className="text-white/55 text-sm">
        Pair with the <strong className="text-white/80">UI tab → Full-stack local dev</strong> for env vars and {isNext ? "Next rewrites" : "Vite proxy"}.
      </p>
    </div>
  );
}
